name: book_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_core: ^3.6.0  # อัปเดตเวอร์ชันนี้
  flutter_local_notifications: ^14.0.0
  timezone: ^0.9.4
  image_picker: ^1.0.0
  firebase_storage: ^12.3.2  # ใช้เวอร์ชันนี้
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.17.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
